### ISSUE TITLE
Cannot update  freecad-common ( 2:0.19+dfsg1~202103010028~ubuntu20.04.1) on Linux Mint

### ISSUE THREAD

**Issue by pierbout** [FreeCAD/FreeCAD-Enhancement-Proposals#11]
Hello,

I cannot update the last version of freecad-common ( 2:0.19+dfsg1\~202103010028\~ubuntu20.04.1), due to QtCore.py conflict .
I did not have any problem usually...

Message (in french :-) ):
E: /var/cache/apt/archives/freecad-common_2%3a0.19+dfsg1\~202103010028\~ubuntu20.04.1_all.deb: tentative de remplacement de « /usr/share/freecad/Ext/PySide/QtCore.py », qui appartient aussi au paquet freecad-runtime 2:0.18.4+dfsg2~202007252144\~ubuntu20.04.1

**Translation:
E: /var/cache/apt/archives/freecad-common_2%3a0.19+dfsg1\~202103010028\~ubuntu20.04.1_all.deb:trying to replace « /usr/share/freecad/Ext/PySide/QtCore.py », which also belong to the package freecad-runtime 2:0.18.4+dfsg2~202007252144\~ubuntu20.04.1**

![image](https://user-images.githubusercontent.com/70711916/112822171-e0b6e780-9087-11eb-82db-d03fa1e7dd44.png)

**Comment by luzpaz** [comment]
Totally wrong place for this :stuck_out_tongue_closed_eyes:   
This looks like something you should report to the the downstream ubuntu packagers. You may want to use the [AppImage](wiki.freecadweb.org/AppImage) instead?
